# Generated by Django 4.0 on 2023-09-16 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_course_disp'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dateof',
            field=models.DateField(default=datetime.datetime(2023, 9, 16, 20, 0, 15, 738099)),
        ),
    ]
